export type WebsiteProduct = {
  slug: string;
  name: string;
  category: string;
  headline: string;
  summary: string;
  description: string;
  image: string;
  imageAlt: string;
  tone: string;
  services: string[];
  deliverables: string[];
  challenge: string;
  approach: string;
  experience: string[];
  palette: [string, string, string];
  layout: "editorial" | "commerce" | "saas" | "education" | "wellness" | "property" | "professional" | "travel" | "event" | "industrial" | "beauty" | "restaurant";
};

export const websiteProducts: WebsiteProduct[] = [
  {
    slug: "blue-bean-coffee",
    name: "Blue Bean Coffee",
    category: "F&B · Landing Page Concept",
    headline: "Kể câu chuyện thương hiệu trước khi mời khách đặt bàn.",
    summary: "Landing page F&B giàu hình ảnh, menu trực quan và luồng đặt bàn gọn.",
    description: "Một concept website dành cho thương hiệu cà phê muốn tạo cảm giác thủ công, gần gũi nhưng vẫn hiện đại trên mọi thiết bị.",
    image: "/images/project-cafe-unsplash.jpg",
    imageAlt: "Concept landing page Blue Bean Coffee",
    tone: "#d9c5a5",
    services: ["Brand direction", "UI/UX design", "Responsive website", "Booking flow"],
    deliverables: ["Kiến trúc nội dung", "Hero storytelling", "Menu sản phẩm", "Luồng đặt bàn", "Thiết kế mobile", "SEO nền tảng"],
    challenge: "Nhiều website F&B chỉ hiển thị menu và địa chỉ, chưa truyền được không khí thương hiệu hoặc tạo động lực để khách đặt bàn.",
    approach: "DolphinX xây cấu trúc theo nhịp kể chuyện: cảm xúc thương hiệu, món nổi bật, không gian, bằng chứng trải nghiệm và CTA đặt bàn đúng thời điểm.",
    experience: ["Trang chủ giàu hình ảnh", "Menu có phân nhóm", "Đặt bàn ít bước", "Bản đồ và giờ mở cửa"],
    palette: ["#2d2119", "#d79b61", "#f4eadc"],
    layout: "editorial",
  },
  {
    slug: "mono-collection",
    name: "MONO Collection",
    category: "Retail · Commerce Concept",
    headline: "Một cửa hàng số tinh gọn cho thương hiệu bán lẻ hiện đại.",
    summary: "Website catalog kết hợp membership, sản phẩm và trải nghiệm đa kênh.",
    description: "Concept commerce ưu tiên hình ảnh sản phẩm, khả năng khám phá bộ sưu tập và kết nối hành trình thành viên.",
    image: "/images/project-retail-unsplash.jpg",
    imageAlt: "Concept website bán lẻ MONO Collection",
    tone: "#d8eaf7",
    services: ["Commerce UX", "UI system", "Product catalog", "Membership journey"],
    deliverables: ["Danh mục sản phẩm", "Bộ lọc thông minh", "Trang chi tiết", "Giỏ hàng", "Membership", "Thiết kế mobile"],
    challenge: "Khách cần xem được sản phẩm nhanh nhưng thương hiệu vẫn phải giữ cảm giác cao cấp, nhất quán giữa website và cửa hàng.",
    approach: "Hệ thống bố cục tối giản để sản phẩm dẫn dắt thị giác, kết hợp các điểm chạm thành viên và ưu đãi mà không làm gián đoạn hành trình mua.",
    experience: ["Bộ sưu tập theo mùa", "Trang sản phẩm rõ ràng", "Thành viên đa kênh", "CTA mua hàng nhất quán"],
    palette: ["#111827", "#6daed6", "#edf6fb"],
    layout: "commerce",
  },
  {
    slug: "flowdesk-ai",
    name: "FlowDesk AI",
    category: "SaaS · Product Website Concept",
    headline: "Biến một sản phẩm phức tạp thành câu chuyện dễ hiểu.",
    summary: "Product website cho nền tảng AI vận hành, CRM và tự động hoá dữ liệu.",
    description: "Concept SaaS kết hợp website marketing với visual dashboard để người xem hiểu sản phẩm trước khi đăng ký tư vấn.",
    image: "/images/dolphinx-ai-operations-concept.png",
    imageAlt: "Concept website SaaS FlowDesk AI",
    tone: "#cfeeff",
    services: ["Product storytelling", "SaaS UI", "Dashboard visual", "Conversion design"],
    deliverables: ["Value proposition", "Feature bento", "Dashboard preview", "Use cases", "Pricing structure", "Demo CTA"],
    challenge: "Sản phẩm AI và automation thường nhiều thuật ngữ, khiến khách hàng khó hình dung lợi ích trước khi được demo trực tiếp.",
    approach: "DolphinX chuyển tính năng thành các tình huống vận hành cụ thể, dùng dashboard visual và micro-copy để giảm tải nhận thức.",
    experience: ["Hero tập trung giá trị", "Feature bento", "Visual sản phẩm thật", "Luồng đăng ký demo"],
    palette: ["#071c4b", "#13c7e9", "#edf8ff"],
    layout: "saas",
  },
  {
    slug: "brightpath-academy",
    name: "BrightPath Academy",
    category: "Giáo dục · Landing Page Concept",
    headline: "Biến chương trình đào tạo thành một lộ trình dễ lựa chọn.",
    summary: "Landing page tuyển sinh với khóa học, lịch khai giảng và form tư vấn rõ ràng.",
    description: "Concept dành cho trung tâm ngoại ngữ và đào tạo muốn thể hiện phương pháp học, đội ngũ và kết quả đầu ra một cách đáng tin cậy.",
    image: "/images/startup-meeting-pexels.jpg",
    imageAlt: "Concept landing page trung tâm giáo dục BrightPath Academy",
    tone: "#fff0c7",
    services: ["Education UX", "Course catalog", "Lead form", "SEO content"],
    deliverables: ["Trang tuyển sinh", "Danh sách khóa học", "Lịch khai giảng", "Giảng viên", "Form tư vấn", "FAQ học viên"],
    challenge: "Nội dung khóa học thường dài và khó so sánh, khiến phụ huynh hoặc học viên chưa biết nên bắt đầu từ đâu.",
    approach: "Phân tầng nội dung theo nhu cầu, trình độ và kết quả đầu ra; đặt form tư vấn ở các điểm ra quyết định thay vì xuất hiện dày đặc.",
    experience: ["Tìm khóa học theo mục tiêu", "Lịch khai giảng rõ ràng", "Hồ sơ giảng viên", "Đăng ký tư vấn nhanh"],
    palette: ["#2b2467", "#ffcc47", "#fff9e8"],
    layout: "education",
  },
  {
    slug: "an-nhien-wellness",
    name: "An Nhiên Wellness",
    category: "Wellness · Service Website Concept",
    headline: "Một trải nghiệm số nhẹ nhàng trước cả buổi hẹn đầu tiên.",
    summary: "Website spa và wellness với liệu trình, chuyên gia và luồng đặt lịch tinh gọn.",
    description: "Concept dịch vụ chăm sóc sức khoẻ chú trọng cảm giác yên tâm, nội dung dễ hiểu và khả năng đặt lịch trên thiết bị di động.",
    image: "/images/vietnamese-retail-team.png",
    imageAlt: "Concept website An Nhiên Wellness",
    tone: "#dcece3",
    services: ["Service UX", "Booking flow", "Content design", "Mobile first"],
    deliverables: ["Danh mục liệu trình", "Trang chuyên gia", "Bảng giá", "Đặt lịch", "Câu hỏi thường gặp", "Thiết kế mobile"],
    challenge: "Dịch vụ wellness cần truyền tải sự tin cậy nhưng vẫn giữ cảm giác nhẹ nhàng, tránh nội dung phô trương hoặc gây áp lực mua.",
    approach: "Sử dụng nhịp nội dung thoáng, giải thích quy trình rõ ràng và đưa bằng chứng chuyên môn vào đúng điểm người dùng cần reassurance.",
    experience: ["Khám phá liệu trình", "Chọn chuyên gia", "Đặt lịch theo thời gian", "Nhắc lịch tự động"],
    palette: ["#173f35", "#91b9a4", "#eff7f2"],
    layout: "wellness",
  },
  {
    slug: "horizon-residence",
    name: "Horizon Residence",
    category: "Bất động sản · Project Website Concept",
    headline: "Đưa vị trí, tiện ích và giá trị đầu tư vào một câu chuyện thống nhất.",
    summary: "Landing page dự án bất động sản với mặt bằng, tiện ích và đăng ký tham quan.",
    description: "Concept dự án nhà ở ưu tiên hình ảnh lớn, thông tin pháp lý dễ tìm và hành trình nhận brochure hoặc đặt lịch tham quan.",
    image: "/images/startup-meeting-pexels.jpg",
    imageAlt: "Concept website dự án Horizon Residence",
    tone: "#e8dfca",
    services: ["Property storytelling", "Lead generation", "Interactive plan", "Performance"],
    deliverables: ["Tổng quan dự án", "Vị trí", "Tiện ích", "Mặt bằng", "Thư viện", "Form nhận brochure"],
    challenge: "Landing page bất động sản dễ trở nên dài, nặng hình và thiếu thứ tự ưu tiên thông tin cho từng nhóm người mua.",
    approach: "Xây hành trình từ bối cảnh sống đến thông tin ra quyết định, tối ưu ảnh theo từng thiết bị và giữ CTA nhất quán.",
    experience: ["Khám phá vị trí", "Xem mặt bằng", "Tải brochure", "Đặt lịch tham quan"],
    palette: ["#183331", "#c6a76f", "#f5f1e8"],
    layout: "property",
  },
  {
    slug: "northstar-legal",
    name: "Northstar Legal",
    category: "Chuyên gia · Corporate Website Concept",
    headline: "Biến chuyên môn thành sự tin cậy ngay từ lần truy cập đầu tiên.",
    summary: "Website doanh nghiệp dịch vụ chuyên môn với lĩnh vực tư vấn và hồ sơ đội ngũ.",
    description: "Concept cho công ty luật, tư vấn và dịch vụ B2B cần hình ảnh chín chắn, nội dung có cấu trúc và liên hệ rõ ràng.",
    image: "/images/software-team-pexels.jpg",
    imageAlt: "Concept corporate website Northstar Legal",
    tone: "#dce3ea",
    services: ["Corporate UX", "Content strategy", "Expert profiles", "Technical SEO"],
    deliverables: ["Trang năng lực", "Lĩnh vực tư vấn", "Hồ sơ chuyên gia", "Insights", "Case notes", "Liên hệ"],
    challenge: "Nội dung chuyên môn thường nhiều chữ và thuật ngữ, nhưng khách hàng cần nhanh chóng biết đội ngũ có phù hợp với vấn đề của họ hay không.",
    approach: "Tổ chức website theo tình huống cần hỗ trợ, kết hợp hồ sơ chuyên gia và bài phân tích để tạo niềm tin tự nhiên.",
    experience: ["Tìm lĩnh vực tư vấn", "Xem hồ sơ chuyên gia", "Đọc phân tích", "Gửi yêu cầu bảo mật"],
    palette: ["#101d2b", "#b8c9d8", "#f2f5f7"],
    layout: "professional",
  },
  {
    slug: "go-quang-ngai",
    name: "Go Quảng Ngãi",
    category: "Du lịch · Destination Concept",
    headline: "Một hành trình địa phương bắt đầu từ những điều đáng nhớ.",
    summary: "Website du lịch với điểm đến, lịch trình và trải nghiệm bản địa.",
    description: "Concept cẩm nang du lịch địa phương giúp du khách khám phá theo thời gian, sở thích và khoảng cách di chuyển.",
    image: "/images/project-cafe-unsplash.jpg",
    imageAlt: "Concept website du lịch Go Quảng Ngãi",
    tone: "#dff3ef",
    services: ["Destination UX", "Content hub", "Trip planner", "Local SEO"],
    deliverables: ["Điểm đến", "Lịch trình gợi ý", "Bản đồ", "Ẩm thực", "Lưu trú", "Cẩm nang"],
    challenge: "Thông tin du lịch địa phương thường phân tán, thiếu lộ trình gợi ý và khó hình dung thời gian cần thiết cho mỗi trải nghiệm.",
    approach: "Nhóm điểm đến theo kiểu chuyến đi và tạo các itinerary ngắn để người dùng có thể bắt đầu lập kế hoạch ngay.",
    experience: ["Khám phá theo sở thích", "Lưu lịch trình", "Xem bản đồ", "Tìm trải nghiệm địa phương"],
    palette: ["#073c48", "#20b9a8", "#ecfaf6"],
    layout: "travel",
  },
  {
    slug: "founder-day-2026",
    name: "Founder Day 2026",
    category: "Sự kiện · Registration Concept",
    headline: "Tạo đủ hứng thú để khách đăng ký trước khi họ cuộn hết trang.",
    summary: "Landing page sự kiện với diễn giả, lịch trình và vé tham dự.",
    description: "Concept cho hội thảo và sự kiện startup cần thông điệp mạnh, lịch trình dễ theo dõi và đăng ký nhanh.",
    image: "/images/startup-meeting-pexels.jpg",
    imageAlt: "Concept landing page sự kiện Founder Day 2026",
    tone: "#e7dcff",
    services: ["Event identity", "Landing page", "Ticket flow", "Analytics"],
    deliverables: ["Hero sự kiện", "Danh sách diễn giả", "Agenda", "Hạng vé", "Đối tác", "Form đăng ký"],
    challenge: "Trang sự kiện phải truyền được năng lượng và giá trị tham gia trong khi vẫn cung cấp đủ thông tin thực tế.",
    approach: "Đưa chủ đề, diễn giả nổi bật và CTA vé lên sớm; lịch trình được chia theo phiên để quét nhanh trên mobile.",
    experience: ["Xem diễn giả", "Lọc agenda", "Chọn hạng vé", "Nhận vé qua email"],
    palette: ["#21113f", "#8f5cff", "#f3eeff"],
    layout: "event",
  },
  {
    slug: "vietbuild-engineering",
    name: "VietBuild Engineering",
    category: "Công nghiệp · B2B Website Concept",
    headline: "Năng lực kỹ thuật được trình bày bằng bằng chứng, không bằng khẩu hiệu.",
    summary: "Corporate website B2B với dự án, năng lực nhà máy và hồ sơ kỹ thuật.",
    description: "Concept dành cho doanh nghiệp xây dựng và sản xuất cần trình bày năng lực rõ ràng với đối tác trong và ngoài nước.",
    image: "/images/software-team-pexels.jpg",
    imageAlt: "Concept website VietBuild Engineering",
    tone: "#dce7ef",
    services: ["B2B UX", "Project library", "Capability deck", "Bilingual structure"],
    deliverables: ["Hồ sơ năng lực", "Dự án", "Dịch vụ kỹ thuật", "Chứng nhận", "Tài liệu", "Liên hệ B2B"],
    challenge: "Website công nghiệp thường nhiều tài liệu nhưng thiếu lớp trình bày giúp đối tác nhanh chóng đánh giá năng lực phù hợp.",
    approach: "Xây thư viện dự án có bộ lọc, đưa số liệu và chứng nhận gần nội dung dịch vụ, hỗ trợ cấu trúc song ngữ.",
    experience: ["Lọc dự án", "Tải hồ sơ năng lực", "Xem chứng nhận", "Gửi yêu cầu báo giá"],
    palette: ["#132a3e", "#f28a2e", "#edf3f6"],
    layout: "industrial",
  },
  {
    slug: "lumina-beauty",
    name: "Lumina Beauty",
    category: "Mỹ phẩm · Commerce Concept",
    headline: "Để mỗi sản phẩm có đủ không gian kể câu chuyện riêng.",
    summary: "Website mỹ phẩm với routine, thành phần và trải nghiệm mua hàng giàu hình ảnh.",
    description: "Concept thương hiệu beauty kết hợp editorial content và commerce, giúp khách chọn sản phẩm theo nhu cầu da.",
    image: "/images/project-retail-unsplash.jpg",
    imageAlt: "Concept website mỹ phẩm Lumina Beauty",
    tone: "#f5dfe5",
    services: ["Beauty commerce", "Editorial UX", "Product finder", "Membership"],
    deliverables: ["Bộ sưu tập", "Product finder", "Routine", "Thành phần", "Giỏ hàng", "Membership"],
    challenge: "Danh mục mỹ phẩm dễ khiến khách bối rối khi không biết sản phẩm nào phù hợp hoặc nên kết hợp theo thứ tự nào.",
    approach: "Kết nối content tư vấn với danh mục sản phẩm, dùng routine và bộ lọc nhu cầu để giảm tải quyết định.",
    experience: ["Tìm theo nhu cầu da", "Xây routine", "Xem thành phần", "Mua theo bộ"],
    palette: ["#421f2c", "#dc8faa", "#fff3f6"],
    layout: "beauty",
  },
  {
    slug: "bep-nha-bistro",
    name: "Bếp Nhà Bistro",
    category: "Nhà hàng · Booking Concept",
    headline: "Đưa hương vị và không khí của nhà hàng lên màn hình.",
    summary: "Website nhà hàng với menu theo mùa, đặt bàn và câu chuyện nguyên liệu.",
    description: "Concept cho nhà hàng Việt hiện đại muốn kể câu chuyện ẩm thực và tối ưu hành trình đặt bàn theo nhóm.",
    image: "/images/project-cafe-unsplash.jpg",
    imageAlt: "Concept website nhà hàng Bếp Nhà Bistro",
    tone: "#eadfcf",
    services: ["Restaurant UX", "Menu design", "Reservation", "Storytelling"],
    deliverables: ["Menu theo mùa", "Câu chuyện bếp", "Không gian", "Đặt bàn", "Sự kiện riêng", "Bản đồ"],
    challenge: "Menu online thường chỉ là file PDF, khó xem trên điện thoại và không thể hiện được không khí trải nghiệm tại nhà hàng.",
    approach: "Chuyển menu thành nội dung web có phân nhóm, kết hợp hình ảnh không gian và luồng đặt bàn theo số khách, ngày, giờ.",
    experience: ["Xem menu theo mùa", "Chọn không gian", "Đặt bàn", "Nhận xác nhận"],
    palette: ["#351d16", "#c37043", "#f7eee4"],
    layout: "restaurant",
  },
];

export function getWebsiteProduct(slug: string) {
  return websiteProducts.find((product) => product.slug === slug);
}
