"use client";

import { ArrowRight, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { miniAppTemplates } from "../zalo-mini-app/templates";
import { MiniAppPhonePreview } from "./MiniAppPhonePreview";
import { StableLink as Link } from "./StableLink";

export function MiniAppCatalogGrid() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("Tất cả");
  const categories = ["Tất cả", ...Array.from(new Set(miniAppTemplates.map((item) => item.category)))];
  const filtered = useMemo(() => miniAppTemplates.filter((item) => (category === "Tất cả" || item.category === category) && `${item.name} ${item.category} ${item.summary}`.toLocaleLowerCase("vi").includes(query.trim().toLocaleLowerCase("vi"))), [category, query]);

  return <><div className="mt-10 flex flex-col gap-3 rounded-2xl border border-blue-100 bg-white p-3 lg:flex-row"><label className="flex min-h-12 flex-1 items-center gap-3 rounded-xl bg-[#f3f8ff] px-4"><Search size={17} className="text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-xs outline-none" placeholder="Tìm Mini App theo ngành hoặc chức năng..." aria-label="Tìm template Zalo Mini App"/></label><div className="flex gap-2 overflow-x-auto">{categories.map((item) => <button key={item} type="button" onClick={() => setCategory(item)} className={`shrink-0 rounded-xl px-4 py-3 text-[9px] font-bold ${category === item ? "bg-[#075fc2] text-white" : "border border-blue-100 bg-white text-slate-600"}`}>{item}</button>)}</div></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((template) => <Link href={`/zalo-mini-app/${template.slug}`} key={template.slug} className="group overflow-hidden rounded-[26px] border border-blue-100 bg-white transition hover:-translate-y-1 hover:shadow-[0_28px_70px_rgba(7,45,102,.12)]"><article><div className="relative flex min-h-[460px] items-end justify-center overflow-hidden pt-10" style={{ background: `radial-gradient(circle at 50% 35%, white, ${template.accentSoft})` }}><div className="translate-y-14 transition duration-500 group-hover:translate-y-10"><MiniAppPhonePreview template={template} compact/></div><span className="absolute left-5 top-5 rounded-full bg-white/85 px-3 py-2 text-[8px] font-black tracking-[.1em] backdrop-blur-xl" style={{ color: template.accent }}>{template.category.toUpperCase()}</span></div><div className="p-6"><h3 className="font-[family-name:var(--display)] text-2xl font-semibold tracking-[-.04em] text-[#071c4b]">{template.name}</h3><p className="mt-3 min-h-12 text-xs leading-6 text-slate-500">{template.summary}</p><span className="mt-6 inline-flex items-center gap-2 text-[10px] font-bold" style={{ color: template.accent }}>Xem chi tiết template <ArrowRight size={15}/></span></div></article></Link>)}<Link href="/#contact" className="grid min-h-[560px] place-content-center rounded-[26px] border border-dashed border-blue-300 bg-blue-50 p-8 text-center"><Sparkles size={34} className="mx-auto text-[#075fc2]"/><h3 className="mt-5 font-[family-name:var(--display)] text-2xl font-semibold text-[#071c4b]">Thiết kế Mini App riêng</h3><p className="mx-auto mt-3 max-w-xs text-xs leading-6 text-slate-500">Thiết kế module, hành trình và tích hợp dữ liệu theo đúng mô hình kinh doanh.</p><span className="mt-6 inline-flex items-center justify-center gap-2 text-[10px] font-bold text-[#075fc2]">Yêu cầu tư vấn <ArrowRight size={15}/></span></Link></div>{filtered.length === 0 && <div className="mt-8 rounded-2xl bg-white p-10 text-center text-sm text-slate-500">Chưa có template trùng từ khoá. DolphinX có thể thiết kế Mini App riêng.</div>}</>;
}
