import Image from "next/image";
import { ArrowUpRight, BarChart3, CalendarDays, MapPin, ShoppingBag, Sparkles } from "lucide-react";
import type { WebsiteProduct } from "../website/products";

export function WebsiteConceptCover({ product, detail = false }: { product: WebsiteProduct; detail?: boolean }) {
  const [ink, accent, surface] = product.palette;
  const words = product.headline.split(" ").slice(0, 8).join(" ");
  const commerce = product.layout === "commerce" || product.layout === "beauty";
  const editorial = product.layout === "editorial" || product.layout === "restaurant" || product.layout === "wellness";
  const data = product.layout === "saas" || product.layout === "industrial";

  return (
    <div className={`relative isolate flex h-full min-h-[500px] items-center justify-center overflow-hidden p-5 md:p-9 ${detail ? "min-h-[680px]" : ""}`} style={{ background: `radial-gradient(circle at 85% 12%, ${accent}55, transparent 32%), ${surface}` }}>
      <div className="absolute -left-20 top-1/3 h-72 w-72 rounded-full border opacity-30" style={{ borderColor: accent }}/>
      <div className="absolute -right-24 -top-24 h-80 w-80 rounded-full opacity-15 blur-3xl" style={{ background: accent }}/>
      <div className={`relative w-full max-w-[980px] overflow-hidden rounded-[18px] border-[7px] shadow-[0_35px_85px_rgba(14,27,47,.26)] ${detail ? "scale-100" : "scale-[.96]"}`} style={{ borderColor: ink, background: "#fff" }}>
        <div className="flex h-8 items-center gap-1.5 px-3" style={{ background: ink }}><i className="h-1.5 w-1.5 rounded-full bg-red-400"/><i className="h-1.5 w-1.5 rounded-full bg-amber-300"/><i className="h-1.5 w-1.5 rounded-full bg-emerald-400"/><span className="ml-3 text-[7px] text-white/45">{product.slug}.dolphinx.demo</span></div>
        <div className="flex h-12 items-center justify-between border-b px-5" style={{ color: ink }}><b className="font-[family-name:var(--display)] text-[10px] tracking-[-.03em]">{product.name}</b><div className="flex gap-4 text-[6px] font-bold opacity-60"><span>Giới thiệu</span><span>Dịch vụ</span><span>Dự án</span></div><span className="rounded-full px-3 py-1.5 text-[6px] font-black" style={{ background: accent, color: ink }}>LIÊN HỆ</span></div>

        {commerce ? (
          <div className="grid min-h-[400px] grid-cols-[.78fr_1.22fr]" style={{ background: surface, color: ink }}><div className="flex flex-col justify-center p-8"><small className="text-[7px] font-black tracking-[.16em]" style={{ color: accent }}>NEW COLLECTION</small><h3 className="mt-4 font-[family-name:var(--display)] text-4xl font-semibold leading-[.95] tracking-[-.065em]">{words}</h3><p className="mt-5 text-[8px] leading-4 opacity-60">Khám phá bộ sưu tập được chọn lọc cho trải nghiệm mỗi ngày.</p><span className="mt-6 flex w-fit items-center gap-2 rounded-full px-4 py-2 text-[7px] font-bold" style={{ background: ink, color: surface }}><ShoppingBag size={10}/>Mua ngay</span></div><div className="grid grid-cols-2 gap-2 p-4">{[0,1,2,3].map((item)=><div key={item} className="relative overflow-hidden rounded-xl" style={{ background: item === 0 ? accent : `${ink}${item === 3 ? "22" : "12"}` }}><span className="absolute bottom-3 left-3 rounded-full bg-white/85 px-2 py-1 text-[6px] font-bold">Collection 0{item+1}</span><i className="absolute -right-6 -top-6 h-24 w-24 rounded-full border-[18px] opacity-30" style={{ borderColor: item === 0 ? surface : accent }}/></div>)}</div></div>
        ) : data ? (
          <div className="grid min-h-[400px] grid-cols-[.9fr_1.1fr] p-7" style={{ background: surface, color: ink }}><div className="flex flex-col justify-center pr-8"><small className="text-[7px] font-black tracking-[.16em]" style={{ color: accent }}>SMARTER OPERATIONS</small><h3 className="mt-4 font-[family-name:var(--display)] text-4xl font-semibold leading-[.96] tracking-[-.06em]">{words}</h3><p className="mt-5 text-[8px] leading-4 opacity-60">Một hệ thống rõ ràng để đội ngũ nhìn thấy điều quan trọng và hành động nhanh hơn.</p></div><div className="my-auto rounded-2xl border bg-white p-4 shadow-xl" style={{ borderColor: `${accent}35` }}><div className="flex items-center justify-between"><span className="text-[7px] font-bold">Tổng quan vận hành</span><BarChart3 size={14} style={{ color: accent }}/></div><div className="mt-4 grid grid-cols-3 gap-2">{["24.8K","+38%","98.4%"].map((item)=><div key={item} className="rounded-lg p-3" style={{ background: surface }}><b className="block text-[12px]">{item}</b><small className="text-[5px] opacity-50">Hiệu suất</small></div>)}</div><div className="mt-3 flex h-28 items-end gap-2 rounded-lg p-3" style={{ background: surface }}>{[42,75,55,88,66,94,72].map((height,index)=><i key={index} className="flex-1 rounded-t" style={{ height: `${height}%`, background: index===5 ? accent : `${accent}55` }}/>)}</div></div></div>
        ) : editorial ? (
          <div className="grid min-h-[400px] grid-cols-[1.05fr_.95fr]" style={{ background: surface, color: ink }}><div className="flex flex-col justify-center p-8"><small className="text-[7px] font-black tracking-[.16em]" style={{ color: accent }}>A DISTINCT EXPERIENCE</small><h3 className="mt-4 font-[family-name:var(--display)] text-[42px] font-semibold leading-[.95] tracking-[-.05em]">{words}</h3><p className="mt-5 max-w-sm text-[8px] leading-4 opacity-60">Những chi tiết nhỏ tạo nên một trải nghiệm được ghi nhớ.</p><span className="mt-7 flex items-center gap-2 text-[7px] font-black">KHÁM PHÁ <ArrowUpRight size={10}/></span></div><div className="relative m-3 min-h-[360px] overflow-hidden rounded-xl"><Image src={product.image} alt={product.imageAlt} fill sizes="500px" className="object-cover"/><div className="absolute inset-0" style={{ background:`linear-gradient(180deg,transparent,${ink}66)` }}/><span className="absolute bottom-4 left-4 text-[7px] font-bold text-white">DolphinX visual concept · 2026</span></div></div>
        ) : (
          <div className="relative min-h-[400px] overflow-hidden p-8" style={{ background: ink, color: "#fff" }}><div className="relative z-10 max-w-[58%]"><small className="text-[7px] font-black tracking-[.16em]" style={{ color: accent }}>{product.category.split("·")[0].toUpperCase()}</small><h3 className="mt-4 font-[family-name:var(--display)] text-4xl font-semibold leading-[.95] tracking-[-.065em]">{words}</h3><p className="mt-5 text-[8px] leading-4 text-white/55">Nội dung được thiết kế quanh hành trình thật của khách hàng.</p><div className="mt-6 flex gap-2"><span className="rounded-full px-3 py-2 text-[6px] font-bold" style={{ background: accent, color: ink }}>Bắt đầu</span><span className="rounded-full border border-white/20 px-3 py-2 text-[6px]">Xem chi tiết</span></div></div><div className="absolute -bottom-16 -right-6 grid h-[330px] w-[44%] rotate-3 grid-cols-2 gap-2 rounded-[28px] border border-white/10 bg-white/8 p-3 backdrop-blur-md">{[Sparkles,CalendarDays,MapPin,ArrowUpRight].map((Icon,index)=><div key={index} className="rounded-xl bg-white p-4" style={{ color:ink }}><Icon size={14} style={{ color:accent }}/><i className="mt-8 block h-2 w-2/3 rounded" style={{ background:`${ink}22` }}/><i className="mt-2 block h-2 w-full rounded" style={{ background:`${ink}12` }}/></div>)}</div></div>
        )}
      </div>
      <span className="absolute bottom-5 left-5 rounded-full border border-white/50 bg-white/80 px-3 py-2 text-[7px] font-black tracking-[.12em] backdrop-blur-xl" style={{ color:ink }}>DOLPHINX · CONCEPT DEMO</span>
    </div>
  );
}
