import Image from "next/image";
import { ArrowRight, Blocks, Gauge, LayoutTemplate, MonitorSmartphone, Palette, RefreshCcw, SearchCheck, Sparkles } from "lucide-react";
import { StableLink as Link } from "./StableLink";

export function WebsiteUpgradeBuilder() {
  return <>
    <section className="px-4 py-24"><div className="mx-auto max-w-[1200px]"><div className="grid items-end gap-8 md:grid-cols-2"><div><span className="text-[10px] font-black tracking-[.16em] text-[#075fc2]">WEBSITE REVAMP · CŨ THÀNH MỚI</span><h2 className="dx-heading-gradient mt-4 font-[family-name:var(--display)] text-4xl font-semibold leading-tight tracking-[-.05em] md:text-6xl">Giữ giá trị thương hiệu. Làm mới toàn bộ trải nghiệm.</h2></div><p className="text-sm leading-7 text-slate-600">DolphinX kiểm tra website cũ từ nội dung, tốc độ, SEO đến khả năng chuyển đổi; sau đó xây lại cấu trúc và giao diện mà không làm mất dữ liệu quan trọng.</p></div><div className="mt-14 grid gap-5 md:grid-cols-2"><div className="overflow-hidden rounded-[28px] border border-slate-200 bg-[#eceff3] p-5"><div className="relative aspect-[16/10] overflow-hidden rounded-xl bg-white shadow-xl"><Image src="/images/theme-references/automotive.jpg" alt="Ảnh chụp một website ô tô thực tế trước khi được đánh giá và làm mới" fill sizes="(max-width:768px) 100vw,50vw" className="object-cover object-top grayscale-[18%] contrast-[.92]"/><div className="absolute inset-0 bg-gradient-to-t from-[#061634]/35 via-transparent to-transparent"/><span className="absolute left-3 top-3 rounded-full bg-white/90 px-3 py-2 text-[7px] font-black text-slate-600 shadow-sm backdrop-blur">GIAO DIỆN THẬT · TRƯỚC KHI AUDIT</span></div><div className="mt-5 flex items-center justify-between gap-4"><span><small className="block text-[8px] font-black tracking-[.14em] text-slate-400">TRƯỚC</small><b className="mt-2 block text-lg">Nhiều thông tin · Khó ưu tiên · CTA chưa rõ</b></span><RefreshCcw className="shrink-0 text-slate-400"/></div></div><div className="overflow-hidden rounded-[28px] border border-blue-100 bg-blue-50 p-5"><div className="relative aspect-[16/10] overflow-hidden rounded-xl bg-white shadow-xl"><Image src="/images/theme-references/agency.jpg" alt="Mẫu website mới tham khảo từ ThemeWP" fill sizes="(max-width:768px) 100vw,50vw" className="object-cover object-top"/><span className="absolute left-3 top-3 rounded-full bg-[#071c4b]/85 px-3 py-2 text-[7px] font-black text-cyan-200">MẪU THAM KHẢO · THEMEWP</span></div><div className="mt-5 flex items-center justify-between gap-4"><span><small className="block text-[8px] font-black tracking-[.14em] text-[#075fc2]">SAU</small><b className="mt-2 block text-lg">Rõ thông điệp · Nhanh · Dễ hành động</b></span><Sparkles className="shrink-0 text-[#075fc2]"/></div></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[SearchCheck,"Audit SEO & nội dung"],[Gauge,"Tối ưu tốc độ"],[MonitorSmartphone,"Làm mới responsive"],[RefreshCcw,"Chuyển dữ liệu an toàn"]].map(([Icon,label])=>{const I=Icon as typeof SearchCheck;return <div key={String(label)} className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white p-5 text-xs font-bold"><I size={19} className="text-[#075fc2]"/>{String(label)}</div>})}</div></div></section>
    <section className="bg-[#071c4b] px-4 py-24 text-white"><div className="mx-auto grid max-w-[1200px] items-center gap-12 md:grid-cols-2"><div><span className="text-[10px] font-black tracking-[.16em] text-cyan-300">DOLPHINX WEB STUDIO</span><h2 className="dx-heading-gradient-light mt-5 font-[family-name:var(--display)] text-4xl font-semibold leading-tight tracking-[-.05em] md:text-6xl">Tự thiết kế website online, không cần bắt đầu từ trang trắng.</h2><p className="mt-6 max-w-xl text-sm leading-7 text-slate-300">Chọn template, kéo các section, đổi màu thương hiệu và xem trước desktop–mobile ngay trong trình thiết kế. Khi cần triển khai thật, bạn có thể gửi bản nháp cho DolphinX tiếp tục hoàn thiện.</p><Link href="/studio" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-xl bg-cyan-300 px-6 text-xs font-bold text-[#071c4b]">Mở trình thiết kế online <ArrowRight size={17}/></Link></div><div className="grid gap-3 sm:grid-cols-2">{[[LayoutTemplate,"Template theo ngành","Chọn cấu trúc gần với mục tiêu kinh doanh."],[Blocks,"Thư viện section","Thêm hero, lợi ích, sản phẩm, review và CTA."],[Palette,"Nhận diện thương hiệu","Đổi màu, nội dung và phong cách trực tiếp."],[MonitorSmartphone,"Xem trước responsive","Kiểm tra desktop, tablet và mobile trước khi gửi."]].map(([Icon,title,text])=>{const I=Icon as typeof LayoutTemplate;return <article key={String(title)} className="rounded-[24px] border border-white/10 bg-white/5 p-7"><I size={23} className="text-cyan-300"/><h3 className="mt-7 text-base font-bold">{String(title)}</h3><p className="mt-3 text-xs leading-6 text-slate-400">{String(text)}</p></article>})}</div></div></section>
  </>;
}
